versi alpha1 untuk naik ke versi 1.2
bgli/kbbi-qt pull request #116
Opened 2017-08-14 04:43 UTC by sasongko26

Perbaikan masalah minor, tetapi tidak ada salahnya dinaikkan versinya. Setelah mencermati menu dan berkas KBBI-Qt.desktop, ternyata shortcut untuk KBBI Qt tidak bisa tampil di menu Education/Pendidikan (setidaknya terjadi di Slackware saya). Padahal informasi dari berkas KBBI-Qt.desktop seharusnya bisa tampil, tetapi yang tampil hanya di menu Office/Perkantoran.

2017-08-14 06:19 UTC, suciptoid requested changes
Terimakasih banyak pak atas perbaikanya. Tapi untuk secreenshot saya lihat kembali ke versi lawas (versi buram). Tolong berikan screenshot terbaru (yang tidak buram tentunya) atau gunakan screenshot sebelumnya.

2017-08-14 06:20 UTC, showcheap commented
@sasongko26 Terimakasih perbaikanya pak. Tolong screenshot diperbarui ya 😇

2017-08-14 07:35 UTC, alunux commented
Mungkin commitnya juga bisa disederhanain atau dirapiin.

2017-08-14 08:51 UTC, rafeyu commented
@sasongko26 Oiya pak, entry version pada KBBI-Qt.desktop jangan diubah (tetap 1.0), karena itu bukan merujuk versi aplikasi tapi versi spec .desktop.

Referensi: https://wiki.archlinux.org/index.php/Desktop_entries#Key_definition

2017-08-17 04:43 UTC, showcheap commented
🆙 @sasongko26

2018-07-06 02:12 UTC, suciptoid approved these changes

2018-07-06 02:13 UTC, merged