Penambahan nama pengembang dan penghapusan Bantuan
bgli/kbbi-qt pull request #30
Opened 2016-11-01 05:40 UTC by raniaamina

2016-11-01 06:25 UTC, alunux commented
@raniaamina brach-nya konflik, mungkin bisa di-rebase dulu.

2016-11-01 06:41 UTC, suciptoid requested changes
Masih konflik @raniaamina

2016-11-02 03:11 UTC, showcheap commented
@raniaamina UP

2016-11-02 04:15 UTC, suciptoid approved these changes

2016-11-02 04:16 UTC, merged