debian package amd64
bgli/kbbi-qt pull request #42
Opened 2016-11-03 15:42 UTC by antosamalona

Please try before merged :+1:

2016-11-03 15:44 UTC, showcheap commented
@antosamalona kedepanya pull request diarahkan ke branch dev ya pak 👍 
terimakasih kontribusinya di pemaketan. 😬

2016-11-03 16:06 UTC, suciptoid requested changes
Yang diunggah bukan hasil kompilasinya pak, monggo di lihat contoh dari pak alunux
https://github.com/bgli/kbbi-qt/pull/17

2016-11-03 16:07 UTC, closed without merging

2016-11-05 09:34 UTC, antosamalona commented
Berarti maksdnya dibikinkan ppa?

2016-11-05 10:29 UTC, alunux commented
Bisa juga, kang @antosamalona. Tapi yang dimaksud di sini adalah resep untuk membuat DEBnya, kang. Kalau RPM, ada berkas SPEC. Kalau DEB, ada apa aja? Kalau gak salah folder debian yang berisi rules ya?

2016-11-05 17:40 UTC, antosamalona commented
Ooh.. gitu, oke

2016-11-05 19:23 UTC, alunux commented
@antosamalona Coba akang lihat ini https://github.com/linuxmint/mint-y-theme/tree/master/debian