Update README.md
bgli/kbbi-qt pull request #77
Opened 2016-11-11 12:45 UTC by raniaamina

2016-11-11 14:54 UTC, suciptoid reviewed
Yang di folder debian apa kehapus pak @raniaamina ?

2016-11-11 15:39 UTC, raniaamina commented
wah, iya pak . . .
waktu perbaikan tadi saya rupanya pull ke master bukan dev, sehingga tidak muncul folder debian...

2016-11-11 16:16 UTC, showcheap commented
@raniaamina wah, coba di benerin dulu pak 💃

2016-11-11 16:17 UTC, suciptoid requested changes
Folder debian hilang

2016-11-16 03:49 UTC, showcheap commented
ping @raniaamina

2016-11-16 05:29 UTC, raniaamina commented
sudah ada folder debian-nya lagi pak

2016-11-16 12:32 UTC, suciptoid approved these changes

2016-11-16 17:41 UTC, raniaamina commented
lah, kok masih bermasalah??

2016-11-16 23:19 UTC, merged